### PR TITLE
Corrected Outbound Message Structure for Attachments data

### LINKED ISSUE #4: json: cannot unmarshal string into Go struct field
Looks like there is a bug in the library that is trying to json unmarshal an OutboundMessage.Attachment into the type postmark.Attachment.

The exact error message I am getting is ```json: cannot unmarshal string into Go struct field OutboundMessage.Attachments of type postmark.Attachment```

Let me know if you want me to provide more information or if you want I can submit a PR to fix this.

### PR DESCRIPTION
**Pull request by phillipCouto**
Fixes #4.

This postmark api returns an array of filenames for the attachments field in the OutboundMessage object.

Updated the unit test as well to make sure this is tested correctly in the future.

### CODE REVIEW

**Comment by phillipCouto** [comment]
Also I have informed Postmark to update their documentation to add an example of the Attachments array in their example response for the Outbound Email api call.

**Comment by phillipCouto** [comment]
@keighl just a poke to review when you get a chance.

**Comment by keighl** [comment]
Sorry it's taken me forever to look at this @phillipCouto. Thanks for digging into their spec. But the `Email` struct uses `Attachment` too and it needs the full payload. Perhaps we simply change `OutboundMessage.Attachments` to `[]string`?

**Comment by phillipCouto** [comment]
That is what I did, is it not?

**Comment by keighl** [comment]
Lolz, you're right. I can't read, I guess.

**Comment by keighl** [comment]
Thanks for your contribution! Very much appreciated

**Comment by phillipCouto** [comment]
Not a problem anytime =)

**Pull request merged**
