### PR TITLE
Send only needed headers

### PR DESCRIPTION
**Pull request by kudrykv**
Explicitly set what tokens request function has to send. Otherwise, Postmark will produce an error.

### CODE REVIEW

**Comment by kudrykv** [comment]
Has to resolve [this issue](https://github.com/keighl/postmark/issues/1).

**Comment by keighl** [comment]
Hey @kudrykv, this looks great! Very much appreciated

1) Let's not export the new `options` type, since users don't interact with `doRequest`.

2) Instead of separate attributes for token inclusion (`IncludeServerToken`, `IncludeServerToken`), perhaps a single `TokenType` field? E.g

```go
err := client.doRequest(options{
    Method: "GET",
    Path: path,
    TokenType: "server",
 }, &res)
```

**Comment by kudrykv** [comment]
@keighl if I lowercase `options` struct name, it becomes inaccessible through other files in the package.

**Comment by keighl** [comment]
@kudrykv not exporting `options` makes it inaccessible to **_other_** packages... which is what we want.

**Comment by kudrykv** [comment]
@keighl my bad. I just lowercased `options`. Other functions already use this keyword, so I got errors in tests. This is why I renamed `Options` to `parameters`.

**Comment by keighl** [comment]
Perfect, thanks for the help @kudrykv

**Pull request merged**
